import { time } from "console";
import * as vscode from "vscode";

export function writeFlaggedFilesPathsInSummaryFile(
  flaggedFiles: Set<string>,
  workspaceFolders: readonly vscode.WorkspaceFolder[]
): void {

  const summaryFileUri: vscode.Uri = vscode.Uri.parse(
    `${workspaceFolders[0].uri.toString()}/SECURE_COMMIT_FLAGGED_FILES.md`
  );

  var date = new Date().toLocaleDateString();
  var time = new Date().toLocaleTimeString("en-EN", {
  hour: "2-digit",
  minute: "2-digit",
  second: "2-digit",
  fractionalSecondDigits: 3, 
  hour12: true
});;
  var summaryFileTitle: string = `*Automatically generated by Secure Commit on ${date} at ${time}*\n`;
  var summaryFileText : string = summaryFileTitle + "## The following files contains sensitive info that should likely not appear in your commit :";

  flaggedFiles.forEach((flaggedFilePath) => {
    summaryFileText += `\n - ${flaggedFilePath}`
  })

  const content: Uint8Array = new TextEncoder().encode(summaryFileText);

  vscode.workspace.fs.writeFile(summaryFileUri, content);
}
